### ISSUE TITLE
The ldap3 library was not found. This is required to use LDAP authentication (see requirements.txt).

### ISSUE THREAD

**Issue by maltiwankhade** [getredash/contrib-helm-chart#81]
While working on LDAP settings from helm chart getting error for ldap3 library, when checked in Docker hub images for Redash there is different image name mentioned to be used when Ldap we will be implementing for Redash. 
https://hub.docker.com/layers/redash/redash/latest/images/sha256-55cedc91a09107e894a0ce872d138ec8c708ec537f6df282207bdf14eec72491?context=explore
![image](https://user-images.githubusercontent.com/83571615/117103066-41c49000-ad97-11eb-9490-664f622bfa28.png)

Could you please check the image once used in helm chart ?? Also is there any fixes possible for mentioned error? 
Its a blocker for ldap integrations :(
![image](https://user-images.githubusercontent.com/83571615/117102950-fc07c780-ad96-11eb-9bcc-9c924bde31ab.png)

**Comment by grugnog** [comment]
@maltiwankhade I believe you will need to build your own image that includes this library - it's not included by default due to licensing (see comment in https://github.com/getredash/redash/blob/master/requirements.txt#L67 - there is a line in there that you can uncomment).
You can then update your chart configuration to point at to your own image.
