### ISSUE TITLE
helm chart for redash version 10

### ISSUE THREAD

**Issue by juanvasquezreyes** [getredash/contrib-helm-chart#87]
Is there a plan to upgrade helm chart for redash version 10?

**Comment by grugnog** [comment]
I am indeed interested in this, although may not have time to work on it for a while - I am open to PRs - the CI does test the upgrade path already.
Given the switch from Celery to RQ I think this will require a new major version of the chart. Since Helm 2 is now end-of-life I am thinking we should drop support for that se we can take advantage of Helm 3 features going forward also.

**Comment by grugnog** [comment]
Big thanks to @minato128 for working on this in #105 - I merged and added some documentation tweaks and this is building as 3.0.0-beta1.

**Comment by minato128** [comment]
@grugnog Thank you 👍 
If there is anything I can do to help, please let me know.
